### ISSUE TITLE
new session is created for each call

### ISSUE THREAD

**Issue by cordoba** [jebas/connect-pg#1]
I already had a working code storing connect session to a noSQL backend. I wanted switch connect-pg. But each call generates a new session. What could be the reason? Seems everything works, even the data that I attached to the session is stored in the database, but each call generates a new session. Thanks.

**Comment by jebas** [comment]
Sorry it took a little bit of time to get back to you.  I'm right now dealing with a new born, so my extra time is limited.

This issue might be how your browser is setup.  If it is not storing and returning cookies, Express or Connect will assume that each call is a new session.  Therefore each call will have its own session id.

Just to make sure that there wasn't an issue with the code, I brought it up in Chrome, Firefox, and Midori.  The default setups for Chrome and Firefox worked as expected.  Only one session id was generated and updated for all of the calls.  Midori, which I had cookies turned off, generated three session ids per test page.  Additionally, each refresh generated three more ids.  

Hopefully, this was some useful information.

**Comment by cordoba** [comment]
Congratulations. What a coincidence, we're expecting a baby next week too. 

I found the problem. The version of the connect module pg-connect use is different than the one I have. I use 2.0.0alpha1 version and pg-connect comes with the version 1.8.5. After pointing it to mine with a symlink it worked. 

Thanks for the reply, and enjoy the newborn.
